Modified randoop
leusonmario/randoop pull request #2
Opened 2021-04-14 18:46 UTC by ToniMaciel

Now, solving a typo that was causing a bug when creates the csv reports.

2021-04-14 22:15 UTC, leusonmario requested changes

2021-04-14 22:15 UTC, leusonmario commented on src/main/java/randoop/main/GenTests.java
> -      try {
Essa exceção não é mais levantada? Ou você está tratando ela em outro lugar?

2021-04-14 22:15 UTC, leusonmario commented on src/main/java/randoop/util/Report.java
> +            PrintWriter writer = new PrintWriter(new File("methods_report(ModifiedRandoop).csv"));
Talvez poderia deixar o mesmo nome do arquivo, considerando que quando rodamos o estudo, tudo gerado por uma versão da ferramenta, seja possível de ser rastreado.

2021-04-15 16:50 UTC, ToniMaciel commented on src/main/java/randoop/main/GenTests.java
> -      try {
Ela não é mais levantada. Quem poderia lançar essa exceção era a linha 71 do Report.java. Como esse método de comparação agora usa a dependência externa, a exceção não é lançada.

2021-04-16 18:05 UTC, leusonmario approved these changes

2021-04-20 19:59 UTC, merged